changelog:
  categories:
    - title: 🐛 Bugs eradicated
      labels:
        - Bug
    - title: 🦾 Improvements made
      labels:
        - Enhancement
    - title: ✨ Features added
      labels:
        - Feature
    - title: 📚 Documentation updated
      labels:
        - Documentation
