<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PSADTNXT.WinGet</RootNamespace>
    <AssemblyName>PSADTNXT.WinGet</AssemblyName>
    <OutputType>Library</OutputType>

    <Company>neo42 GmbH</Company>
    <Title>Neo42.Extension.WinGet Library for PSAppDeployToolkit</Title>
    <Copyright>Copyright © 2026 neo42 GmbH. All rights reserved.</Copyright>
    <Description>Neo42.Extension.WinGet Library for PSAppDeployToolkit</Description>
    <PackageProjectUrl>https://neo42.de/psappdeploytoolkit</PackageProjectUrl>
    <RepositoryUrl>https://github.com/neo42-GmbH/PSAppDeployToolKitExtensions</RepositoryUrl>

    <Deterministic>true</Deterministic>
    <Platforms>AnyCPU</Platforms>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <RootOutputPath>..\..\..\build</RootOutputPath>
    <PublishDir>$(RootOutputPath)\PSAppDeployToolkit.Neo42.Extensions.WinGet\lib\$(TargetFramework)</PublishDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <WarningLevel>3</WarningLevel>
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>
