namespace PSADTNXT.Deployment
{
	public enum DeploymentHookPoint
	{
		CustomBegin,
		CustomInstallAndReinstallAndSoftMigrationBegin,
		CustomSoftMigrationBegin,
		CustomSoftMigrationEnd,
		CustomInstallAndReinstallAndSoftMigrationEnd,
		CustomInstallAndReinstallPreInstallAndReinstall,
		CustomReinstallPreUninstall,
		CustomReinstallPostUninstallOnError,
		CustomReinstallPostUninstall,
		CustomReinstallPreInstall,
		CustomReinstallPostInstallOnError,
		CustomReinstallPostInstall,
		CustomInstallBegin,
		CustomInstallEndOnError,
		CustomInstallEnd,
		CustomInstallAndReinstallEnd,
		CustomUninstallBegin,
		CustomUninstallEndOnError,
		CustomUninstallEnd,
		CustomInstallUserPartBegin,
		CustomInstallUserPartEnd,
		CustomUninstallUserPartBegin,
		CustomUninstallUserPartEnd,
		CustomEnd,
		CustomEndOnError
	}
}
