name: Pester Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: PSAppDeployToolKitExtensions-Runner

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ./NxtExtensions

    - name: Checkout Public Repo
      uses: actions/checkout@v3
      with:
        repository: 'PSAppDeployToolkit/PSAppDeployToolkit.git'
        ref: ${{ vars.TARGET_ADT_VERSION }}
        path: ./PSADT
        
    - name: Run Pester Tests
      shell: powershell
      run: .\NxtExtensions\test\PesterTestsStarter.ps1