name: Pester Tests

on:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ./NxtExtensions

    - name: Checkout Public Repo
      uses: actions/checkout@v3
      with:
        repository: 'PSAppDeployToolkit/PSAppDeployToolkit.git'
        ref: ${{ vars.TARGET_ADT_VERSION }}
        path: ./PSADT
    - name: Run Pester Tests
      shell: powershell
      run: .\NxtExtensions\test\PesterTestsStarter.ps1
