name: Pester Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: PSAppDeployToolKitExtensions-Runner

    steps:

    - name: Checkout PSADT
      uses: actions/checkout@v3
      with:
        repository: 'PSAppDeployToolkit/PSAppDeployToolkit.git'
        ref: ${{ vars.TARGET_ADT_VERSION }}
        sparse-checkout: 'Toolkit/AppDeployToolkit/*'
        sparse-checkout-cone-mode: false
        path: '${{ github.workspace }}\Toolkit'

    - name: Checkout Extensions
      uses: actions/checkout@v3
      with:
        path: '${{ github.workspace }}\Extensions'

    - name: Merge Extensions
      run: |
        Copy-Item -Recurse -Path ${{ github.workspace }}\Extensions\* -Destination ${{ github.workspace }}\Toolkit\ -Force

    - name: Run Pester Tests
      shell: powershell
      run: ${{ github.workspace }}\Toolkit\test\RunPester.ps1
