name: Test Artifact

on:
  workflow_call:

jobs:
  test:
    runs-on: PSAppDeployToolKitExtensions-Runner
    steps:
    - name: download-artifact
      id: download-artifact-test
      uses: actions/download-artifact@v4
      with:
        path: artifact
    
    - name: checkout-tests
      uses: actions/checkout@v4
      with:
        path: test
        sparse-checkout: test/*
        sparse-checkout-cone-mode: false

    - name: run-pester
      shell: powershell
      run: |
        Set-Location -Path "${{ steps.download-artifact-test.outputs.download-path }}\*\PSAppDeployToolkit"
        Copy-Item -Path ".\AppDeployToolkit\AppDeployToolkitLogo.ico" -Destination ".\Setup.ico"
        . ..\..\..\test\test\RunPester.ps1
    
    - name: remove-artifact
      if: always()
      shell: powershell
      run: Remove-Item -Path "${{ steps.download-artifact-test.outputs.download-path }}" -Recurse -Force