name: Test Artifact

on:
  workflow_call:

jobs:
  test:
    runs-on: PSAppDeployToolKitExtensions-Runner
    steps:
    - name: download-artifact
      id: download-artifact-test
      uses: actions/download-artifact@v4
    
    - name: checkout-tests
      uses: actions/checkout@v4
      with:
        sparse-checkout: test/*
        sparse-checkout-cone-mode: false

    - name: run-pester
      shell: powershell
      run: |
        Set-Location -Path "${{ steps.download-artifact-test.outputs.download-path }}\PSAppDeployToolkit"
        Copy-Item -Path ".\AppDeployToolkit\AppDeployToolkitLogo.ico" -Destination ".\Setup.ico"
        . "..\test\RunPester.ps1"