name: Test Artifact

on:
  workflow_call:

jobs:
  test:
    runs-on: PSAppDeployToolKitExtensions-Runner
    steps:
    - name: download-artifact
      id: download-artifact-test
      uses: actions/download-artifact@v4
      with:
        path: artifact

    - name: checkout-tests
      uses: actions/checkout@v4
      with:
        path: test
        sparse-checkout: .tests/*
        sparse-checkout-cone-mode: false

    - name: run-pester
      shell: powershell
      run: |
        $artifactPath = Get-ChildItem -Path "${{ steps.download-artifact-test.outputs.download-path }}" | Select-Object -First 1
        $versionFromPath = Get-ChildItem -Path "$($artifactPath.FullName)" | Where-Object {$_.Name -match '^\d{4}\.\d{2}\.\d{2}\.\d+$'} | Select-Object -First 1 -ExpandProperty BaseName
        Write-Host "Testing artifact version: $versionFromPath"
        Copy-Item -Path "$($artifactPath.FullName)\$versionFromPath\AppDeployToolkit\AppDeployToolkitLogo.ico" -Destination "$($artifactPath.FullName)\$versionFromPath\Setup.ico" -Verbose
        Write-Host "Running Pester tests, Path '$($artifactPath.FullName)\$versionFromPath\AppDeployToolkit\AppDeployToolkitMain.ps1'"
        . .\test\.tests\RunPester.ps1 -ToolkitMain "$($artifactPath.FullName)\$versionFromPath\AppDeployToolkit\AppDeployToolkitMain.ps1"

    - name: remove-artifact
      if: always()
      shell: powershell
      run: Remove-Item -Path "${{ steps.download-artifact-test.outputs.download-path }}" -Recurse -Force
