name: Test Artifact

on:
  workflow_call:

jobs:
  test:
    runs-on: PSAppDeployToolKitExtensions-Runner
    steps:
    - name: download-artifact
      id: download-artifact-test
      uses: actions/download-artifact@v4
      with:
        path: artifact
    
    - name: checkout-tests
      uses: actions/checkout@v4
      with:
        path: test
        sparse-checkout: test/*
        sparse-checkout-cone-mode: false

    - name: run-pester
      shell: powershell
      run: |
        [System.IO.FileInfo]$deployAppPath = Get-ChildItem -Recurse -Path "${{ steps.download-artifact-test.outputs.download-path }}" -Filter "PSAppDeployToolkit\Deploy-Application.ps1" | Select-Object -First 1
        [System.IO.FileInfo]$pesterTest = Get-ChildItem -Recurse -Path "test" -Filter "RunPester.ps1" | Select-Object -First 1
        Set-Location -Path $deployAppPath.DirectoryName
        Copy-Item -Path ".\AppDeployToolkit\AppDeployToolkitLogo.ico" -Destination ".\Setup.ico"
        . $pesterTest.FullName